# Simple workflow for deploying static content to GitHub Pages
name: Build, test and export data, deploy static content to Pages

on:
  schedule:
    - cron: "0 */12 * * *" # UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  issues: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  build-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4 # python version is set default by .python-version file
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run dbt and create db file
        run: make db
      - name: Run dbt test
        id: run_test
        run: make test
        continue-on-error: true

      # if dbt test failed, post comment to the issue #1
      - name: Render issue comment template
        if: ${{ steps.run_test.outcome == 'failure' }}
        id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/comment-template.md
          vars: |
            GITHUB_SERVER_URL: $GITHUB_SERVER_URL
            GITHUB_REPOSITORY: $GITHUB_REPOSITORY
            GITHUB_RUN_ID: $GITHUB_RUN_ID
      - name: Post comment to the issue
        if: ${{ steps.run_test.outcome == 'failure' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: 1
          body: ${{ steps.template.outputs.result }}

      # Export, commit files
      - name: Export files
        run: make export
      - name: Commit output files
        id: commit_output
        run: |
          MAKE_ENV=GITHUB_ACTIONS make ga-commit
        continue-on-error: true

      # If committing files succeeded, push to main branch and deploy site
      - name: push
        if: ${{ steps.commit_output.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Build docs
        if: ${{ steps.commit_output.outcome == 'success' }}
        run: make docs
      - name: Setup Pages
        if: ${{ steps.commit_output.outcome == 'success' }}
        uses: actions/configure-pages@v1
      - name: Upload artifact
        if: ${{ steps.commit_output.outcome == 'success' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: './target'
      - name: Deploy to GitHub Pages
        if: ${{ steps.commit_output.outcome == 'success' }}
        id: deployment
        uses: actions/deploy-pages@main
