# Simple workflow for deploying static content to GitHub Pages
name: Build, test and export data, deploy static content to Pages

on:
  schedule:
    - cron: "0 */12 * * *" # UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  build-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4 # python version is set default by .python-version file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run dbt and create db file
        run: make db
      - name: Run tests
        run: make test
        continue-on-error: true
      - name: If tests failed, add comment to the issue
        if: ${{ steps.error_execution.outcome == 'failure' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: 1
          body: |
            `dbt test` command failed.
            Check the [link to log](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}).
      - name: Export files
        run: make export
      - name: Commit output files
        run: |
          MAKE_ENV=GITHUB_ACTIONS make ga-commit
        continue-on-error: true
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        continue-on-error: true
      - name: Build docs
        run: make docs
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './target'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
